theme: jekyll-theme-minimal
title: Давайте создадим простую базу данных
description: Пишем клон sqlite на C с нуля
google_analytics: UA-105767942-1
collections:
  parts:
    output: true
defaults:
  - scope:
      path: ""
      type: parts
    values:
      layout: default
